---
- name: firewall | firewalld | Enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: true
    masked: false
    state: started

- name: firewall | firewalld | Enable OpenVPN Port (firewalld)
  ansible.posix.firewalld:
    port: "{{ openvpn_port }}/{{ openvpn_proto }}"
    zone: "{{ firewalld_default_interface_zone }}"
    permanent: true
    immediate: true
    state: enabled

- name: firewall | firewalld | Set tun0 interface to internal
  ansible.posix.firewalld:
    interface: tun0
    zone: internal
    permanent: true
    immediate: true
    state: enabled

- name: firewall | firewalld | Set default interface to external
  ansible.posix.firewalld:
    interface: "{{ ansible_default_ipv4.interface }}"
    zone: "{{ firewalld_default_interface_zone }}"
    permanent: true
    immediate: true
    state: enabled

- name: firewall | firewalld | Enable masquerading on external zone
  ansible.posix.firewalld:
    masquerade: true
    zone: "{{ firewalld_default_interface_zone }}"
    permanent: true
    state: enabled
    # Workaround ansible issue: https://github.com/ansible/ansible/pull/21693
    # immediate: true
  notify:
    - Restart firewalld

# workaround for --permanent not working on non-NetworkManager managed ifaces
# https://bugzilla.redhat.com/show_bug.cgi?id=1112742
- name: firewall | firewalld | Check if ifcfg file exists for {{ ansible_default_ipv4.interface }}
  ansible.builtin.stat:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
  register: __ifcfg

- name: firewall | firewalld | Persist default interface in ifcfg file
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    regexp: "^ZONE="
    line: "ZONE={{ firewalld_default_interface_zone }}"
  when: __ifcfg.stat.exists
