---
- name: firewall | iptables | Change facts to use netfilter-persistent on Debian >= 9 or Ubuntu >= 16
  ansible.builtin.set_fact:
    iptables_save_command: "/usr/sbin/netfilter-persistent save"
    iptables_service: netfilter-persistent
  when: >-
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9)
    or
    (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: firewall | iptables | Install iptables-persistent (Debian/Ubuntu)
  ansible.builtin.package:
    name: "{{ iptables_persistent_package_name }}"
    state: present
  register: __iptables_installed
  when: ansible_os_family == "Debian"

- name: firewall | iptables | Install iptables-services (RedHat/CentOS)
  ansible.builtin.package:
    name: "{{ iptables_services_package_name }}"
    state: present
  register: __iptables_installed
  when: ansible_os_family == "RedHat"

- name: firewall | iptables | Allow VPN forwarding - iptables
  ansible.builtin.iptables:
    chain: FORWARD
    source: "{{ openvpn_server_network }}/24"
    jump: ACCEPT
    action: insert
    comment: "Allow VPN forwarding"
  notify: "Save iptables"

- name: firewall | iptables | Allow incoming SSH connections - iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ansible_port | default(22) }}"
    jump: ACCEPT
    action: insert
    comment: "Allow incoming SSH connection"
  notify: "Save iptables"

- name: firewall | iptables | Allow incoming VPN connections - iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ openvpn_proto }}"
    destination_port: "{{ openvpn_port }}"
    jump: ACCEPT
    action: insert
    comment: "Allow incoming VPN connection"
  notify: "Save iptables"

- name: firewall | iptables | Accept packets from VPN tunnel adaptor - iptables
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: tun0
    jump: ACCEPT
    action: insert
    comment: "Accept packets from VPN tunnel adaptor"
  notify: "Save iptables"

- name: firewall | iptables | Perform NAT readdressing - iptables
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ openvpn_server_network }}/24"
    destination: "! {{ openvpn_server_network }}/24"
    to_source: "{{ ansible_default_ipv4.address }}"
    jump: SNAT
    action: insert
    comment: "Perform NAT readdressing"
  when: openvpn_masquerade_not_snat is falsy and openvpn_no_nat is falsy
  notify: "Save iptables"

- name: firewall | iptables | Perform NAT readdressing with MASQUERADE - iptables
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ openvpn_server_network }}/24"
    destination: "! {{ openvpn_server_network }}/24"
    jump: MASQUERADE
    action: insert
    comment: "Perform NAT readdressing"
  when: openvpn_masquerade_not_snat is truthy and openvpn_no_nat is falsy
  notify:
    - Save iptables

- name: firewall | iptables | Save existing iptables rule before start iptables service
  ansible.builtin.shell: "{{ iptables_save_command }}" # noqa command-instead-of-shell
  when: __iptables_installed.changed is truthy # noqa no-handler
  changed_when: true

- name: firewall | iptables | Enable iptables
  ansible.builtin.service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started
