# generate client keys
---
- name: generate client key
  command: openssl req -nodes -newkey rsa:4096 -keyout {{item}}.key -out {{item}}.csr -days 3650 -subj /CN=OpenVPN-Client-{{item}}/
    chdir=/etc/openvpn/keys
    creates={{item}}.key
  with_items: clients

- name: sign client key
  command: openssl x509 -req -in {{item}}.csr -out {{item}}.crt -CA ca.crt -CAkey ca-key.pem -days 3650
    chdir=/etc/openvpn/keys
    creates={{item}}.crt
  with_items: clients

- name: register server ca key
  command: cat /etc/openvpn/keys/ca.crt
  register: ca_cert
  changed_when: false

- name: register tls-auth key
  command: cat /etc/openvpn/keys/ta.key
  register: tls_auth
  changed_when: false

- name: register client certs
  shell: echo \<cert\> && cat /etc/openvpn/keys/{{item}}.crt && echo \</cert\> && echo \<key\> && cat /etc/openvpn/keys/{{item}}.key && echo \</key\>
  with_items: clients
  register: client_certs
  changed_when: false

- name: generate client config
  template: >
    src=client.ovpn.j2
    dest=/etc/openvpn/{{item.item}}-{{inventory_hostname}}.ovpn
    owner=root
    group=root
    mode=0400
  with_items: client_certs.results

- name: fetch client config
  fetch: >
    src=/etc/openvpn/{{item}}-{{inventory_hostname}}.ovpn
    dest=/tmp/ansible/{{item}}/{{inventory_hostname}}.ovpn
    flat=yes
  with_items: clients
