---
- name: selinux | Check if module was loaded
  ansible.builtin.command: semodule --list-modules
  register: __semodule_loaded
  changed_when: false

- name: selinux | Setup policy
  when:
    - ansible_facts['selinux']['status'] == 'enabled'
    - __semodule_loaded.stdout.find(openvpn_selinux_module) == -1
  block:
    - name: selinux | Copy selinux type enforcement file
      ansible.builtin.template:
        src: "selinux_module.te.j2"
        dest: /var/lib/selinux/{{ openvpn_selinux_module }}.te
        mode: "0644"
    - name: selinux | Make sure selinux policy build RPM is installed
      ansible.builtin.package:
        name: checkpolicy
        state: present
    - name: selinux | Build and install selinux policy
      ansible.builtin.command: "{{ item }}"
      args:
        chdir: /var/lib/selinux
      with_items:
        - "checkmodule -M -m -o {{ openvpn_selinux_module }}.mod {{ openvpn_selinux_module }}.te"
        - "semodule_package -o {{ openvpn_selinux_module }}.pp -m {{ openvpn_selinux_module }}.mod"
        - "semodule -i {{ openvpn_selinux_module }}.pp"
      changed_when: true
