- name: create openvpn key directory
  file: >
    path="{{openvpn_key_dir}}"
    state=directory

- name: Copy openssl extensions
  copy: >
    src="{{item}}"
    dest="{{openvpn_key_dir}}"
    owner=root
    group=root
    mode=0400
  with_items:
    - openssl-server.ext
    - openssl-ca.ext

- name: Generate CA key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout ca-key.pem -out ca-csr.pem -days 3650 -subj /CN=OpenVPN-CA-{{inventory_hostname}}/
    chdir="{{openvpn_key_dir}}"
    creates=ca-key.pem

- name: Sign CA key
  command: openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey ca-key.pem -sha256 -days 3650 -extfile openssl-ca.ext
    chdir="{{openvpn_key_dir}}"
    creates=ca.crt

- name: generate server key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout server.key -out server.csr -days 3650 -subj /CN=OpenVPN-Server-{{inventory_hostname}}/
    chdir="{{openvpn_key_dir}}"
    creates=server.key

- name: protect server key
  file: >
    path="{{openvpn_key_dir}}/server.key"
    mode=0400

- name: sign server key
  command: openssl x509 -req -in server.csr -out server.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -CAcreateserial -extfile openssl-server.ext
    chdir="{{openvpn_key_dir}}"
    creates=server.crt

- name: generate tls-auth key
  command: openvpn --genkey --secret ta.key
    chdir="{{openvpn_key_dir}}"
    creates=ta.key

# not a security issue, params aren't secret, just not generated by an attacker
# per http://security.stackexchange.com/questions/42415/openvpn-dhparam/42418#42418
- name: copy pre-generated DH params
  copy: >
    src=dh.pem
    dest="{{openvpn_key_dir}}"
    owner=root
    group=root
    mode=0400
  when: openvpn_use_pregenerated_dh_params

# Alternatively, if you're concerned about logjam attacks
- name: generate dh params
  command: openssl dhparam -out /etc/openvpn/keys/dh.pem {{openvpn_rsa_bits}}
    chdir="{{openvpn_key_dir}}"
    creates=dh.pem
  when: not openvpn_use_pregenerated_dh_params
